name: Fusion
experiment: hhc
cpu: No
n_vertices: 20

model_specific:
  GNN: # Architecture and model
    arch:
      arch: simple #siamese or simple
      embedding: edge #node or edge
      num_blocks: 5
      original_features_num: 2
      in_features: 64
      out_features: 1
      depth_of_mlp: 3
    train:
      num_examples_train: 100
      num_examples_val: 100
      num_examples_test: 10
      epoch: 1
      batch_size: 16
      lr_stop: !!float 1e-7
      print_freq: 100
      anew: Yes
      opt_args:
        lr: !!float 1e-5
        scheduler_step: 1
        scheduler_decay: 0.1

_hhc:
  problem: hhc
  key_variable: mu
  range_start: 0
  range_end: 25
  steps: 26
  model: GNN
  train_value: 18 #If 'retrain' or 'r', the model will be retrained at each step
  gen_specific:
    generative_model: Gauss
    cycle_param: 0
    path_dataset: dataset_hhc


_sbm:
  problem: sbm
  key_variable: dc
  range_start: 0
  range_end: 6
  steps: 25
  model: GNN
  train_value: 4
  gen_specific:
    c: 3 #The mean degree
    alpha: 0.5
    path_dataset: dataset_sbm


_mcp:
  problem: mcp
  key_variable: planted_size
  range_start: 2 #planted size shouldn't be less than 2
  range_end: 20
  steps: 19
  model: GNN
  train_value: 10
  gen_specific:
    edge_density: 0.5
    path_dataset: dataset_mcp 