---
name: qap_er_bp_inc
cpu: No
root_dir: .
problem: 'qap' #qap, tsp, hhc, tsprl, mcp, sbm
test_enabled: Yes

data:
    train: # Train/Val data generation parameters
        num_examples_train: 20000
        num_examples_val: 1000
        n_vertices: 100

        _qap:
            generative_model: ErdosRenyi # so far ErdosRenyi, Regular or BarabasiAlbert
            noise_model: ErdosRenyi
            edge_density: 0.03
            vertex_proba: 1. # Parameter of the binomial distribution of vertices
            noise: 0.1
            path_dataset: dataset_qap # Path where datasets are stored
        _tsp:
            generative_model: Square01
            distance_used: EUC_2D
            path_dataset: dataset_tsp #TSP #dataset_tsp # Path where datasets are stored
        _hhc:
            generative_model: Gauss
            cycle_param: 0
            fill_param: 5 #Should be largely enough for up to 200 vertices with cycle_param=0
            path_dataset: dataset_hhc
        _mcp:
            edge_density: 0.831763771102671 #0.3981071705534973 #0.1
            clique_size: 4
            planted: No
            path_dataset: dataset_mcp # Path where datasets are stored
        _sbm:
            p_inter : 0.9
            p_outer : 0.1
            alpha: 0.5
            path_dataset: dataset_sbm
            
    test: #Test data generation parameters
        num_examples_test: 1000
        n_vertices: 100
        custom: No #If No, keeps the data_generation from train, just a failsafe so people consciously have to activate custom test
        
        _qap:
            generative_model: ErdosRenyi # so far ErdosRenyi, Regular or BarabasiAlbert
            noise_model: ErdosRenyi
            edge_density: 0.03
            vertex_proba: 1. # Parameter of the binomial distribution of vertices
            noise: 0.1
        _tsp:
            generative_model: Square01
            distance_used: EUC_2D
        _hhc:
            generative_model: Gauss
            cycle_param: 0
            fill_param: 5
        _mcp:
            edge_density: 0.831763771102671 #0.39810717055349726 #0.1
            clique_size: 4
            planted: No
        _sbm:
            p_inter : 0.9
            p_outer : 0.1
            alpha: 0.5


train: # Training parameters
    epoch: 10
    batch_size: 32 #10
    lr: !!float 5e-6 #5e-6
    scheduler_step: 2
    scheduler_decay: 0.7
    lr_stop: !!float 1e-7
    print_freq: 100
    anew: No
    model_path: './runs/qap_er_bp_inc/QAP-50_ErdosRenyi_ErdosRenyi_0.06_1.0_0.1_dataset_qap/' #'/home/mlelarge/GitHub/graph_neural_net/runs/qap_er_bp/QAP-100_ErdosRenyi_ErdosRenyi_0.03_1.0_0.1_dataset_qap'
    #loss_reduction: mean

arch: # Architecture and model
    arch: siamese #siamese or simple
    embedding: node #node or edge
    num_blocks: 2
    original_features_num: 2
    in_features: 64
    out_features: 64
    depth_of_mlp: 3

observers:
    neptune:
        enable: Yes
        project: mautrib/GNN
